version: '3.9'

services:
  postgres_db: 
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    ports: 
     - 5444:5432
    volumes: 
      - ~/apps/postgres:/var/lib/postgresql_db/data
    environment:
      POSTGRES_DB: flashcard-db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - 5050:80

  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    command: start-dev
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_HOST: postgres_keycloak 
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_REALM_NAME: ${KC_REALM_NAME}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KC_PORT}:8080
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak-network

  postgres_keycloak:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql_keycloak/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
 
